import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../../core/supabase/supabase_client_provider.dart';
import '../domain/size_group_model.dart';

final sizeGroupRepositoryProvider = Provider<SizeGroupRepository>((ref) {
  return SizeGroupRepository(ref.watch(supabaseClientProvider));
});

class SizeGroupRepository {
  final SupabaseClient _supabase;

  SizeGroupRepository(this._supabase);

  Future<List<SizeGroupModel>> getSizeGroups() async {
    final response = await _supabase.from('size_groups').select().order('name');
    return response.map((json) => SizeGroupModel.fromJson(json)).toList();
  }

  Future<SizeGroupModel> createSizeGroup(SizeGroupModel sizeGroup) async {
    final data = sizeGroup.toJson()..remove('id'); // ID is auto-generated by DB usually, or generated here
    final response = await _supabase.from('size_groups').insert(data).select().single();
    return SizeGroupModel.fromJson(response);
  }

  Future<SizeGroupModel> updateSizeGroup(SizeGroupModel sizeGroup) async {
    final response = await _supabase
        .from('size_groups')
        .update(sizeGroup.toJson())
        .eq('id', sizeGroup.id)
        .select()
        .single();
    return SizeGroupModel.fromJson(response);
  }

  Future<void> deleteSizeGroup(String id) async {
    await _supabase.from('size_groups').delete().eq('id', id);
  }
}
